[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "flyrank-backend-ai-intern"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[tool.hatch.build.targets.wheel]
packages = ["src/flyrank"]
